#########################################################
# DO Community Playbooks: Wordpress on Ubuntu 18.04 LAMP
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]


    - name: Install HySplit Things
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ hysplit_things }}"
      tags: [ system ]

      

    - name: Download HySplit
      get_url:
        url: https://www.ready.noaa.gov/data/web/models/hysplit4/linux_trial/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public.tar.gz
        dest: /tmp/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public.tar.gz
      register: hysplit
    

    - name: Unpack HySplit
      unarchive:
        src: /tmp/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public.tar.gz
        dest: ~/
        remote_src: True

    
    - name: Build the default target
      make:
        chdir: /root/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public

