#########################################################
# DO Community Playbooks: Wordpress on Ubuntu 18.04 LAMP
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]


    - name: Install HySplit Things
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ hysplit_things }}"
      tags: [ system ]

      
    - name: Install bottle using the 'pip3.3' executable
      ansible.builtin.pip:
        name: bottle
        executable: pip3

    - name: Download HySplit
      get_url:
        url: https://www.ready.noaa.gov/data/web/models/hysplit4/linux_trial/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public.tar.gz
        dest: /tmp/hysplit.v5.2.3_UbuntuOS20.04.4LTS_public.tar.gz
      register: hysplit


